name: BotKit CI

on:
  push:
    branches-ignore:
      - 'main'
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  merge_group:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
